### PR TITLE
remove unnecessary regex capture & allow relative reference

### PR DESCRIPTION
**Pull request by amobiz**
allow relative reference according to:
https://tools.ietf.org/html/rfc3986#section-4.2

### CODE REVIEW

**Comment by iefserge** [comment]
@amobiz thank you, this looks great! can we keen existing test cases in addition too?

**Comment by amobiz** [comment]
@iefserge sure!

**Comment by iefserge** [comment]
@amobiz sorry, I mean both new and existing test cases

**Comment by amobiz** [comment]
@iefserge sorry, it was actually both new and existing test cases, but sorted. Should I separate them like below?

```js
var validUrls = [
  {url: 'https://www.youtube.com/watch?v=YoB8t0B4jx4', id: 'YoB8t0B4jx4'},
  {url: 'https://youtube.com/watch?v=YoB8t0B4jx4', id: 'YoB8t0B4jx4'},
  {url: 'http://www.youtube.com/watch?v=YoB8t0B4jx4', id: 'YoB8t0B4jx4'},
  {url: 'http://youtube.com/watch?v=YoB8t0B4jx4', id: 'YoB8t0B4jx4'},
  {url: 'www.youtube.com/watch?v=YoB8t0B4jx4', id: 'YoB8t0B4jx4'},
  {url: 'youtube.com/watch?v=YoB8t0B4jx4', id: 'YoB8t0B4jx4'},
  {url: 'http://www.youtube.com/v/0zM3nApSvMg?fs=1&amp;hl=en_US&amp;rel=0', id: '0zM3nApSvMg'},
  {url: 'http://www.youtube.com/embed/0zM3nApSvMg?rel=0', id: '0zM3nApSvMg'},
  {url: 'http://www.youtube.com/watch?v=0zM3nApSvMg&feature=feedrec_grec_index', id: '0zM3nApSvMg'},
  {url: 'http://www.youtube.com/watch?v=0zM3nApSvMg', id: '0zM3nApSvMg'},
  {url: 'http://youtu.be/0zM3nApSvMg', id: '0zM3nApSvMg'},
  {url: 'http://youtu.be/vzM3nApSvMg', id: 'vzM3nApSvMg'},
  {url: 'http://www.youtube.com/watch?v=0zM3nApSvMg#t=0m10s', id: '0zM3nApSvMg'},
  {url: 'youtube.com/watch?v=0zM3nApSvMg#t=0m10s', id: '0zM3nApSvMg'},
  
  {url: '//www.youtube.com/embed/0zM3nApSvMg?rel=0', id: '0zM3nApSvMg'},
  {url: '//www.youtube.com/v/0zM3nApSvMg?fs=1&amp;hl=en_US&amp;rel=0', id: '0zM3nApSvMg'},
  {url: '//www.youtube.com/watch?v=0zM3nApSvMg#t=0m10s', id: '0zM3nApSvMg'},
  {url: '//www.youtube.com/watch?v=0zM3nApSvMg&feature=feedrec_grec_index', id: '0zM3nApSvMg'},
  {url: '//www.youtube.com/watch?v=0zM3nApSvMg', id: '0zM3nApSvMg'},
  {url: '//www.youtube.com/watch?v=YoB8t0B4jx4', id: 'YoB8t0B4jx4'},
  {url: '//youtu.be/0zM3nApSvMg', id: '0zM3nApSvMg'},
  {url: '//youtu.be/vzM3nApSvMg', id: 'vzM3nApSvMg'},
  {url: '//youtube.com/watch?v=0zM3nApSvMg#t=0m10s', id: '0zM3nApSvMg'},
  {url: '//youtube.com/watch?v=YoB8t0B4jx4', id: 'YoB8t0B4jx4'}
];
```

**Comment by iefserge** [comment]
@amobiz thanks, unsorted should be fine

**Comment by amobiz** [comment]
@iefserge done, please check if OK. Thanks.

**Comment by kesla** [comment]
Woohhoooo! LGTM!

**Pull request merged**
